benchmark:
  base_dir: ../..
  image_dir: dataset/mscoco_val2017_via_format/mscoco_val2017/*

fps:
  max_example_num: 100

memory_usage:
  max_example_num: 100

accuracy:
  base_dir: ../..
  label_map_file: dataset/mscoco_val2017_via_format/mscoco_label_map.yaml
  annotation_file: dataset/mscoco_val2017_via_format/mscoco_val2017_region_data.json
  iou_threshold: 0.3

object_detection:
  base_dir: ../..
  tflite: True    # True | False
  quantized: False # True | False
  checkpoint: models/object_detection/ssd_mobilenet_v2_coco_2018_03_29_tflite_max50/detect.tflite
  label_map_file: dataset/mscoco_val2017_via_format/mscoco_label_map.yaml
  confidence_score_threshold: 0.5
  save_inference_result:
    file: mscoco_val2017_inference_result_tflite.json
    max_example_num: 5000